Adding Search controller and view
ula0156/onlineShop pull request #7
Opened 2017-08-11 22:05 UTC by ula0156

1) Added search controller, view and model.
2) Added new search box on layout page.
3) Home page displays hyperLinks of products.

2017-08-12 18:10 UTC, simionliviumihai requested changes

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShop.core/Data/ICartProvider.cs
> +        Cart GetCart(string userIdentifier);
Used sessionIdOrLogin for the other method

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShop.core/Data/InMemory/InMemoryCartProvider.cs
> +                // didn't understand how to remove from this dictionary
This is not finished

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShopWeb/Controllers/BooksController.cs
> +        //private ProductsModel db = new ProductsModel();
This is commented. Remove if not needed

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShopWeb/Controllers/BooksController.cs
> +            }
Add empty  line after }

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShopWeb/Controllers/CartController.cs
> +            // HttpContext contains an information about current context
Check if id is null

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShopWeb/Controllers/SearchController.cs
> +        // GET: Search
Why GET?

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShopWeb/Controllers/SongsController.cs
> +        private List<Song> GetfSongs()
Typo: GetSongs instead of GetfSongs

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShopWeb/Models/HomeViewModels.cs
> +    public class HomeViewModelBook
Why do you need this class if it only has a Book inside? Why not use Book directly

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShopWeb/Models/HomeViewModels.cs
> +    public class HomeViewModelSong
Same comment as the book here

2017-08-12 18:10 UTC, simionliviumihai commented on onlineShopWeb/Utility/IdentifierLoginUsers.cs
> +    public static class IdentifierLoginUsers
This class name is strange.

2017-08-13 17:17 UTC, ula0156 commented on onlineShop.core/Data/ICartProvider.cs
> +        Cart GetCart(string userIdentifier);
done

2017-08-13 17:20 UTC, ula0156 commented on onlineShopWeb/Controllers/BooksController.cs
> +        //private ProductsModel db = new ProductsModel();
done

2017-08-13 17:20 UTC, ula0156 commented on onlineShopWeb/Controllers/BooksController.cs
> +            }
done

2017-08-13 17:23 UTC, ula0156 commented on onlineShopWeb/Controllers/CartController.cs
> +            // HttpContext contains an information about current context
done

2017-08-13 17:24 UTC, ula0156 commented on onlineShopWeb/Controllers/SearchController.cs
> +        // GET: Search
removed

2017-08-13 17:25 UTC, ula0156 commented on onlineShopWeb/Controllers/SongsController.cs
> +        private List<Song> GetfSongs()
done

2017-08-13 17:27 UTC, ula0156 commented on onlineShopWeb/Utility/IdentifierLoginUsers.cs
> +    public static class IdentifierLoginUsers
changed it.

2017-08-13 20:30 UTC, ula0156 commented on onlineShopWeb/Models/HomeViewModels.cs
> +    public class HomeViewModelBook
I don't need it. Removed it.

2017-08-13 20:30 UTC, ula0156 commented on onlineShopWeb/Models/HomeViewModels.cs
> +    public class HomeViewModelSong
I don't need it. Removed it.

2017-08-13 20:35 UTC, ula0156 commented on onlineShop.core/Data/InMemory/InMemoryCartProvider.cs
> +                // didn't understand how to remove from this dictionary
done

2017-08-13 20:37 UTC, merged